// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SetGameDbContext))]
    partial class SetGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BoardCard", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("CardsId")
                        .HasColumnType("int");

                    b.HasKey("BoardId", "CardsId");

                    b.HasIndex("CardsId");

                    b.ToTable("BoardCard");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("backend.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Filling")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            Color = 0,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2,
                            Color = 0,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3,
                            Color = 0,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            Color = 0,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2,
                            Color = 0,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3,
                            Color = 0,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1,
                            Color = 0,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 2,
                            Color = 0,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 3,
                            Color = 0,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1,
                            Color = 1,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 2,
                            Color = 1,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 12,
                            Amount = 3,
                            Color = 1,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 13,
                            Amount = 1,
                            Color = 1,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 14,
                            Amount = 2,
                            Color = 1,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 15,
                            Amount = 3,
                            Color = 1,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1,
                            Color = 1,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 17,
                            Amount = 2,
                            Color = 1,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 18,
                            Amount = 3,
                            Color = 1,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 19,
                            Amount = 1,
                            Color = 2,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 20,
                            Amount = 2,
                            Color = 2,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 21,
                            Amount = 3,
                            Color = 2,
                            Filling = 0,
                            Shape = 0
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1,
                            Color = 2,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 23,
                            Amount = 2,
                            Color = 2,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 24,
                            Amount = 3,
                            Color = 2,
                            Filling = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 25,
                            Amount = 1,
                            Color = 2,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 26,
                            Amount = 2,
                            Color = 2,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 27,
                            Amount = 3,
                            Color = 2,
                            Filling = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 28,
                            Amount = 1,
                            Color = 0,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 29,
                            Amount = 2,
                            Color = 0,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 30,
                            Amount = 3,
                            Color = 0,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 1,
                            Color = 0,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 2,
                            Color = 0,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 33,
                            Amount = 3,
                            Color = 0,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 1,
                            Color = 0,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 35,
                            Amount = 2,
                            Color = 0,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 3,
                            Color = 0,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 37,
                            Amount = 1,
                            Color = 1,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = 2,
                            Color = 1,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 39,
                            Amount = 3,
                            Color = 1,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 1,
                            Color = 1,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 41,
                            Amount = 2,
                            Color = 1,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 42,
                            Amount = 3,
                            Color = 1,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 43,
                            Amount = 1,
                            Color = 1,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 44,
                            Amount = 2,
                            Color = 1,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 45,
                            Amount = 3,
                            Color = 1,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 1,
                            Color = 2,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 47,
                            Amount = 2,
                            Color = 2,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 48,
                            Amount = 3,
                            Color = 2,
                            Filling = 0,
                            Shape = 1
                        },
                        new
                        {
                            Id = 49,
                            Amount = 1,
                            Color = 2,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 50,
                            Amount = 2,
                            Color = 2,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 51,
                            Amount = 3,
                            Color = 2,
                            Filling = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 52,
                            Amount = 1,
                            Color = 2,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 53,
                            Amount = 2,
                            Color = 2,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 54,
                            Amount = 3,
                            Color = 2,
                            Filling = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 55,
                            Amount = 1,
                            Color = 0,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 56,
                            Amount = 2,
                            Color = 0,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 57,
                            Amount = 3,
                            Color = 0,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 58,
                            Amount = 1,
                            Color = 0,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 59,
                            Amount = 2,
                            Color = 0,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 60,
                            Amount = 3,
                            Color = 0,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 61,
                            Amount = 1,
                            Color = 0,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 62,
                            Amount = 2,
                            Color = 0,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 63,
                            Amount = 3,
                            Color = 0,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 64,
                            Amount = 1,
                            Color = 1,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 65,
                            Amount = 2,
                            Color = 1,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 66,
                            Amount = 3,
                            Color = 1,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 67,
                            Amount = 1,
                            Color = 1,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 68,
                            Amount = 2,
                            Color = 1,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 69,
                            Amount = 3,
                            Color = 1,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 70,
                            Amount = 1,
                            Color = 1,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 71,
                            Amount = 2,
                            Color = 1,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 72,
                            Amount = 3,
                            Color = 1,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 73,
                            Amount = 1,
                            Color = 2,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 74,
                            Amount = 2,
                            Color = 2,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 75,
                            Amount = 3,
                            Color = 2,
                            Filling = 0,
                            Shape = 2
                        },
                        new
                        {
                            Id = 76,
                            Amount = 1,
                            Color = 2,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 77,
                            Amount = 2,
                            Color = 2,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 78,
                            Amount = 3,
                            Color = 2,
                            Filling = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 79,
                            Amount = 1,
                            Color = 2,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 80,
                            Amount = 2,
                            Color = 2,
                            Filling = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 81,
                            Amount = 3,
                            Color = 2,
                            Filling = 2,
                            Shape = 2
                        });
                });

            modelBuilder.Entity("backend.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("backend.Entities.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BoardCard", b =>
                {
                    b.HasOne("backend.Entities.Board", null)
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Entities.Card", b =>
                {
                    b.HasOne("backend.Entities.Game", null)
                        .WithMany("CardsInBacklog")
                        .HasForeignKey("GameId");

                    b.HasOne("backend.Entities.Set", null)
                        .WithMany("Cards")
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("backend.Entities.Game", b =>
                {
                    b.HasOne("backend.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId");

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Set", b =>
                {
                    b.HasOne("backend.Entities.Game", null)
                        .WithMany("FoundSets")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("backend.Entities.Game", b =>
                {
                    b.Navigation("CardsInBacklog");

                    b.Navigation("FoundSets");
                });

            modelBuilder.Entity("backend.Entities.Set", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
